# Generated by Django 3.1.6 on 2021-02-19 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=13)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('complemento', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.datetime(2021, 2, 19, 14, 25, 37, 943699))),
                ('previsao_entrega', models.DateField(blank=True, null=True)),
                ('tipo_pagamento', models.CharField(max_length=100)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apimarketplace.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(max_length=100)),
                ('id_categoria', models.ManyToManyField(to='apimarketplace.Categoria')),
                ('id_fornecedor', models.ManyToManyField(blank=True, null=True, to='apimarketplace.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAtributo',
            fields=[
                ('id_atributo', models.AutoField(primary_key=True, serialize=False)),
                ('nome_atributo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoEntrega',
            fields=[
                ('id_regiao', models.AutoField(primary_key=True, serialize=False)),
                ('nome_regiao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxaEntrega',
            fields=[
                ('id_regiao', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id_transportadora', models.AutoField(primary_key=True, serialize=False)),
                ('nome_transportadora', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaxaEntregaTransportadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_regiao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apimarketplace.taxaentrega')),
                ('id_transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apimarketplace.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='RegiaoEntregaCidade',
            fields=[
                ('id_cidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cidade', models.CharField(max_length=255, null=True)),
                ('cep', models.CharField(max_length=255)),
                ('id_regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimarketplace.regiaoentrega')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoImagem',
            fields=[
                ('id_imagem', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimarketplace.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAtributoValor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('id_atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimarketplace.produtoatributo')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_pedido_item', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=13)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimarketplace.pedido')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apimarketplace.produto')),
            ],
        ),
    ]
