# Generated by Django 3.1.6 on 2021-02-22 12:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apimarketplace', '0003_auto_20210219_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='django_auth_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 9, 46, 16, 66990)),
        ),
        migrations.AlterField(
            model_name='produtoimagem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='./imagens/'),
        ),
    ]
