# Generated by Django 3.1.6 on 2021-02-22 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimarketplace', '0005_auto_20210222_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='password',
            new_name='senha',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 2, 22, 13, 59, 17, 375368)),
        ),
    ]
