# Generated by Django 3.1.6 on 2021-03-01 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimarketplace', '0007_auto_20210223_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 15, 5, 27, 76641)),
        ),
        migrations.CreateModel(
            name='ProdutoComentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimarketplace.cliente')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimarketplace.produto')),
            ],
        ),
    ]
